export const USER_LOGIN_ADMIN_REQUEST = 'USER_LOGIN_ADMIN_REQUEST'
export const USER_LOGIN_ADMIN_SUCCESS = 'USER_LOGIN_ADMIN_SUCCESS'
export const USER_LOGIN_ADMIN_FAIL = 'USER_LOGIN_ADMIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_LOGIN_SELLER_REQUEST = 'USER_LOGIN_SELLER_REQUEST'
export const USER_LOGIN_SELLER_SUCCESS = 'USER_LOGIN_SELLER_SUCCESS'
export const USER_LOGIN_SELLER_FAIL = 'USER_LOGIN_SELLER_FAIL'

export const USER_LOGIN_BUYER_REQUEST = 'USER_LOGIN_BUYER_REQUEST'
export const USER_LOGIN_BUYER_SUCCESS = 'USER_LOGIN_BUYER_SUCCESS'
export const USER_LOGIN_BUYER_FAIL = 'USER_LOGIN_BUYER_FAIL'

export const USER_REGISTER_SELLER_REQUEST = 'USER_REGISTER_SELLER_REQUEST'
export const USER_REGISTER_SELLER_SUCCESS = 'USER_REGISTER_SELLER_SUCCESS'
export const USER_REGISTER_SELLER_FAIL = 'USER_REGISTER_SELLER_FAIL'

export const USER_REGISTER_BUYER_REQUEST = 'USER_REGISTER_BUYER_REQUEST'
export const USER_REGISTER_BUYER_SUCCESS = 'USER_REGISTER_BUYER_SUCCESS'
export const USER_REGISTER_BUYER_FAIL = 'USER_REGISTER_BUYER_FAIL'